// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1, arg2) {
  return window['go']['services']['ActionsService']['Apply'](arg1, arg2);
}

export function Cancel(arg1) {
  return window['go']['services']['ActionsService']['Cancel'](arg1);
}

export function Catalog() {
  return window['go']['services']['ActionsService']['Catalog']();
}

export function FanOutProfiles() {
  return window['go']['services']['ActionsService']['FanOutProfiles']();
}

export function InstallModule(arg1) {
  return window['go']['services']['ActionsService']['InstallModule'](arg1);
}

export function Plan(arg1, arg2) {
  return window['go']['services']['ActionsService']['Plan'](arg1, arg2);
}

export function PowerShellStatus() {
  return window['go']['services']['ActionsService']['PowerShellStatus']();
}

export function RefreshPowerShell() {
  return window['go']['services']['ActionsService']['RefreshPowerShell']();
}

export function Run(arg1, arg2) {
  return window['go']['services']['ActionsService']['Run'](arg1, arg2);
}

export function RunAcross(arg1, arg2, arg3) {
  return window['go']['services']['ActionsService']['RunAcross'](arg1, arg2, arg3);
}
