// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {secrets} from '../models';
import {services} from '../models';
import {pwsh} from '../models';

export function Apply(arg1:string,arg2:string):Promise<engine.Result>;

export function Cancel(arg1:string):Promise<void>;

export function CancelAcross():Promise<void>;

export function Capabilities():Promise<Array<engine.CapabilityView>>;

export function Catalog():Promise<Array<engine.CatalogEntry>>;

export function FanOutProfiles():Promise<Array<secrets.Profile>>;

export function InstallModule(arg1:string):Promise<services.PowerShellStatus>;

export function InstallPowerShell():Promise<services.PowerShellStatus>;

export function Plan(arg1:string,arg2:Record<string, string>):Promise<engine.Plan>;

export function PowerShellInstallMethod():Promise<pwsh.InstallMethod>;

export function PowerShellStatus():Promise<services.PowerShellStatus>;

export function RefreshPowerShell():Promise<services.PowerShellStatus>;

export function Run(arg1:string,arg2:Record<string, string>):Promise<engine.ReadResult>;

export function RunAcross(arg1:string,arg2:Record<string, string>,arg3:Array<string>):Promise<engine.ReadResult>;
