// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1, arg2) {
  return window['go']['services']['ActionsService']['Apply'](arg1, arg2);
}

export function Cancel(arg1) {
  return window['go']['services']['ActionsService']['Cancel'](arg1);
}

export function Catalog() {
  return window['go']['services']['ActionsService']['Catalog']();
}

export function Plan(arg1, arg2) {
  return window['go']['services']['ActionsService']['Plan'](arg1, arg2);
}
