// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function Apply(arg1:string,arg2:string):Promise<engine.Result>;

export function Cancel(arg1:string):Promise<void>;

export function Catalog():Promise<Array<engine.CatalogEntry>>;

export function Plan(arg1:string,arg2:Record<string, string>):Promise<engine.Plan>;
