// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {json} from '../models';

export function Expiring(arg1:number):Promise<Array<services.ExpiringCredential>>;

export function List(arg1:string,arg2:number):Promise<Array<json.RawMessage>>;
