// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSecret(arg1, arg2, arg3) {
  return window['go']['services']['AppsService']['AddSecret'](arg1, arg2, arg3);
}

export function Expiring(arg1) {
  return window['go']['services']['AppsService']['Expiring'](arg1);
}

export function List(arg1, arg2) {
  return window['go']['services']['AppsService']['List'](arg1, arg2);
}
