// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activity(arg1) {
  return window['go']['services']['AuditService']['Activity'](arg1);
}

export function DirectoryAudits(arg1) {
  return window['go']['services']['AuditService']['DirectoryAudits'](arg1);
}

export function DirectoryAuditsFiltered(arg1, arg2, arg3) {
  return window['go']['services']['AuditService']['DirectoryAuditsFiltered'](arg1, arg2, arg3);
}

export function SignIns(arg1) {
  return window['go']['services']['AuditService']['SignIns'](arg1);
}

export function SignInsFiltered(arg1) {
  return window['go']['services']['AuditService']['SignInsFiltered'](arg1);
}
