// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auditlog} from '../models';
import {json} from '../models';

export function Activity(arg1:number):Promise<Array<auditlog.Entry>>;

export function DirectoryAudits(arg1:number):Promise<Array<json.RawMessage>>;

export function SignIns(arg1:number):Promise<Array<json.RawMessage>>;
