// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auditlog} from '../models';
import {json} from '../models';
import {services} from '../models';

export function Activity(arg1:number):Promise<Array<auditlog.Entry>>;

export function DirectoryAudits(arg1:number):Promise<Array<json.RawMessage>>;

export function DirectoryAuditsFiltered(arg1:string,arg2:number,arg3:number):Promise<Array<json.RawMessage>>;

export function SignIns(arg1:number):Promise<Array<json.RawMessage>>;

export function SignInsFiltered(arg1:services.SignInQuery):Promise<Array<json.RawMessage>>;
