// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function List(arg1:string):Promise<Array<json.RawMessage>>;

export function ResetMFA(arg1:string,arg2:string):Promise<Record<string, any>>;
