// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEvent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['services']['CalendarService']['CreateEvent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function List(arg1, arg2) {
  return window['go']['services']['CalendarService']['List'](arg1, arg2);
}
