// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMember(arg1, arg2, arg3) {
  return window['go']['services']['ChatsService']['AddMember'](arg1, arg2, arg3);
}

export function CreateGroupChat(arg1, arg2) {
  return window['go']['services']['ChatsService']['CreateGroupChat'](arg1, arg2);
}

export function List(arg1, arg2) {
  return window['go']['services']['ChatsService']['List'](arg1, arg2);
}

export function Members(arg1) {
  return window['go']['services']['ChatsService']['Members'](arg1);
}

export function Messages(arg1, arg2) {
  return window['go']['services']['ChatsService']['Messages'](arg1, arg2);
}

export function RemoveMember(arg1, arg2) {
  return window['go']['services']['ChatsService']['RemoveMember'](arg1, arg2);
}
