// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';
import {services} from '../models';

export function AddMember(arg1:string,arg2:string,arg3:boolean):Promise<json.RawMessage>;

export function CreateGroupChat(arg1:string,arg2:Array<string>):Promise<json.RawMessage>;

export function List(arg1:string,arg2:number):Promise<Array<json.RawMessage>>;

export function ListForPicker(arg1:string):Promise<Array<services.ChatPickItem>>;

export function Members(arg1:string):Promise<Array<json.RawMessage>>;

export function Messages(arg1:string,arg2:number):Promise<Array<json.RawMessage>>;

export function RemoveMember(arg1:string,arg2:string):Promise<void>;
