// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['services']['CleanupService']['CancelScan']();
}

export function DeleteItems(arg1, arg2) {
  return window['go']['services']['CleanupService']['DeleteItems'](arg1, arg2);
}

export function FindDuplicates(arg1, arg2) {
  return window['go']['services']['CleanupService']['FindDuplicates'](arg1, arg2);
}

export function FindVersionBloat(arg1, arg2, arg3, arg4) {
  return window['go']['services']['CleanupService']['FindVersionBloat'](arg1, arg2, arg3, arg4);
}

export function TrimVersions(arg1, arg2, arg3) {
  return window['go']['services']['CleanupService']['TrimVersions'](arg1, arg2, arg3);
}

export function TrimVersionsMany(arg1, arg2, arg3) {
  return window['go']['services']['CleanupService']['TrimVersionsMany'](arg1, arg2, arg3);
}
