// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function DeleteItems(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<Record<string, any>>;

export function FindDuplicates(arg1:string,arg2:string):Promise<Array<services.DupGroup>>;
