// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CancelScan():Promise<void>;

export function DeleteItems(arg1:Array<string>,arg2:string):Promise<Record<string, any>>;

export function FindDuplicates(arg1:string,arg2:string):Promise<Array<services.DupGroup>>;

export function FindVersionBloat(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<services.VersionBloat>>;

export function TrimVersions(arg1:string,arg2:number,arg3:string):Promise<Record<string, any>>;

export function TrimVersionsMany(arg1:Array<string>,arg2:number,arg3:string):Promise<Array<services.TrimResult>>;
