// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['services']['ConnectService']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['services']['ConnectService']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['services']['ConnectService']['Disconnect']();
}

export function Domains() {
  return window['go']['services']['ConnectService']['Domains']();
}

export function GetStatus() {
  return window['go']['services']['ConnectService']['GetStatus']();
}

export function Profiles() {
  return window['go']['services']['ConnectService']['Profiles']();
}

export function SaveProfile(arg1, arg2) {
  return window['go']['services']['ConnectService']['SaveProfile'](arg1, arg2);
}

export function SetReadOnly(arg1) {
  return window['go']['services']['ConnectService']['SetReadOnly'](arg1);
}
