// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {secrets} from '../models';

export function Connect(arg1:services.ConnectRequest):Promise<services.Status>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function Domains():Promise<Array<string>>;

export function GetStatus():Promise<services.Status>;

export function Profiles():Promise<Array<secrets.Profile>>;

export function SaveProfile(arg1:secrets.Profile,arg2:string):Promise<secrets.Profile>;

export function SetReadOnly(arg1:boolean):Promise<services.Status>;
