// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function BitLockerKey(arg1:string):Promise<json.RawMessage>;

export function BitLockerKeys(arg1:number):Promise<Array<json.RawMessage>>;

export function BitLockerKeysForDevice(arg1:string):Promise<Array<json.RawMessage>>;

export function Delete(arg1:string,arg2:string):Promise<void>;

export function Disable(arg1:string):Promise<void>;

export function Enable(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<json.RawMessage>;

export function List(arg1:string,arg2:number):Promise<Array<json.RawMessage>>;
