// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BitLockerKey(arg1) {
  return window['go']['services']['DevicesService']['BitLockerKey'](arg1);
}

export function BitLockerKeys(arg1) {
  return window['go']['services']['DevicesService']['BitLockerKeys'](arg1);
}

export function Delete(arg1, arg2) {
  return window['go']['services']['DevicesService']['Delete'](arg1, arg2);
}

export function Disable(arg1) {
  return window['go']['services']['DevicesService']['Disable'](arg1);
}

export function Enable(arg1) {
  return window['go']['services']['DevicesService']['Enable'](arg1);
}

export function Get(arg1) {
  return window['go']['services']['DevicesService']['Get'](arg1);
}

export function List(arg1, arg2) {
  return window['go']['services']['DevicesService']['List'](arg1, arg2);
}
