// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';
import {services} from '../models';

export function Children(arg1:string,arg2:string,arg3:string):Promise<Array<json.RawMessage>>;

export function CopyBetweenUsers(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<services.CopyResult>;

export function CreateLink(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<json.RawMessage>;

export function Delete(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Download(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ListRoot(arg1:string,arg2:string):Promise<Array<json.RawMessage>>;

export function OffboardingPreview(arg1:string):Promise<services.CopyPreview>;

export function PickTarget(arg1:Array<string>,arg2:number):Promise<string>;

export function Quota(arg1:string):Promise<services.DriveQuota>;

export function Search(arg1:string,arg2:string,arg3:string):Promise<Array<json.RawMessage>>;

export function Sites(arg1:string):Promise<Array<json.RawMessage>>;

export function Upload(arg1:string,arg2:string,arg3:string):Promise<json.RawMessage>;
