// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer() {
  return window['go']['services']['DriveService']['CancelTransfer']();
}

export function Children(arg1, arg2, arg3) {
  return window['go']['services']['DriveService']['Children'](arg1, arg2, arg3);
}

export function CopyBetweenUsers(arg1, arg2, arg3, arg4) {
  return window['go']['services']['DriveService']['CopyBetweenUsers'](arg1, arg2, arg3, arg4);
}

export function CreateLink(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['DriveService']['CreateLink'](arg1, arg2, arg3, arg4, arg5);
}

export function Delete(arg1, arg2, arg3, arg4) {
  return window['go']['services']['DriveService']['Delete'](arg1, arg2, arg3, arg4);
}

export function Download(arg1, arg2, arg3, arg4) {
  return window['go']['services']['DriveService']['Download'](arg1, arg2, arg3, arg4);
}

export function ListRoot(arg1, arg2) {
  return window['go']['services']['DriveService']['ListRoot'](arg1, arg2);
}

export function OffboardingPreview(arg1) {
  return window['go']['services']['DriveService']['OffboardingPreview'](arg1);
}

export function PickTarget(arg1, arg2) {
  return window['go']['services']['DriveService']['PickTarget'](arg1, arg2);
}

export function Quota(arg1) {
  return window['go']['services']['DriveService']['Quota'](arg1);
}

export function ResumeCopy(arg1) {
  return window['go']['services']['DriveService']['ResumeCopy'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['services']['DriveService']['Search'](arg1, arg2, arg3);
}

export function Sites(arg1) {
  return window['go']['services']['DriveService']['Sites'](arg1);
}

export function SitesWithUsage(arg1) {
  return window['go']['services']['DriveService']['SitesWithUsage'](arg1);
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['services']['DriveService']['Upload'](arg1, arg2, arg3);
}
