// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMember(arg1, arg2) {
  return window['go']['services']['GroupsService']['AddMember'](arg1, arg2);
}

export function AddOwner(arg1, arg2) {
  return window['go']['services']['GroupsService']['AddOwner'](arg1, arg2);
}

export function CreateM365(arg1, arg2, arg3, arg4) {
  return window['go']['services']['GroupsService']['CreateM365'](arg1, arg2, arg3, arg4);
}

export function Get(arg1) {
  return window['go']['services']['GroupsService']['Get'](arg1);
}

export function List(arg1, arg2) {
  return window['go']['services']['GroupsService']['List'](arg1, arg2);
}

export function Members(arg1) {
  return window['go']['services']['GroupsService']['Members'](arg1);
}
