// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function AddMember(arg1:string,arg2:string):Promise<void>;

export function AddOwner(arg1:string,arg2:string):Promise<void>;

export function CreateM365(arg1:string,arg2:string,arg3:string,arg4:string):Promise<json.RawMessage>;

export function Get(arg1:string):Promise<json.RawMessage>;

export function List(arg1:string,arg2:number):Promise<Array<json.RawMessage>>;

export function Members(arg1:string):Promise<Array<json.RawMessage>>;
