// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Device(arg1) {
  return window['go']['services']['IntuneService']['Device'](arg1);
}

export function Devices(arg1) {
  return window['go']['services']['IntuneService']['Devices'](arg1);
}

export function RemoteLock(arg1, arg2) {
  return window['go']['services']['IntuneService']['RemoteLock'](arg1, arg2);
}

export function Retire(arg1, arg2) {
  return window['go']['services']['IntuneService']['Retire'](arg1, arg2);
}

export function Wipe(arg1, arg2, arg3, arg4) {
  return window['go']['services']['IntuneService']['Wipe'](arg1, arg2, arg3, arg4);
}
