// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function Device(arg1:string):Promise<json.RawMessage>;

export function Devices(arg1:number):Promise<Array<json.RawMessage>>;

export function RemoteLock(arg1:string,arg2:string):Promise<void>;

export function Retire(arg1:string,arg2:string):Promise<void>;

export function Wipe(arg1:string,arg2:boolean,arg3:boolean,arg4:string):Promise<void>;
