// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {journal} from '../models';

export function Get(arg1:string):Promise<journal.Run>;

export function List(arg1:number):Promise<Array<journal.RunSummary>>;
