// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Assign(arg1, arg2, arg3) {
  return window['go']['services']['LicensingService']['Assign'](arg1, arg2, arg3);
}

export function Skus() {
  return window['go']['services']['LicensingService']['Skus']();
}
