// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function Assign(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<json.RawMessage>;

export function Skus():Promise<Array<json.RawMessage>>;
