// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Details(arg1, arg2) {
  return window['go']['services']['MailTraceService']['Details'](arg1, arg2);
}

export function Prerequisite() {
  return window['go']['services']['MailTraceService']['Prerequisite']();
}

export function Provision() {
  return window['go']['services']['MailTraceService']['Provision']();
}

export function Trace(arg1) {
  return window['go']['services']['MailTraceService']['Trace'](arg1);
}
