// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Cancel():Promise<void>;

export function Copy(arg1:services.MailboxCopyRequest):Promise<services.MailboxCopyResult>;

export function Preview(arg1:string):Promise<services.MailboxPreview>;
