// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['services']['MailboxTransferService']['Cancel']();
}

export function Copy(arg1) {
  return window['go']['services']['MailboxTransferService']['Copy'](arg1);
}

export function Preview(arg1) {
  return window['go']['services']['MailboxTransferService']['Preview'](arg1);
}
