// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';
import {services} from '../models';

export function Details(arg1:string,arg2:string):Promise<Array<json.RawMessage>>;

export function Prerequisite():Promise<boolean>;

export function Provision():Promise<void>;

export function Trace(arg1:services.TraceQuery):Promise<Array<json.RawMessage>>;
