// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function List(arg1, arg2, arg3) {
  return window['go']['services']['MailService']['List'](arg1, arg2, arg3);
}

export function Send(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['MailService']['Send'](arg1, arg2, arg3, arg4, arg5);
}
