// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function List(arg1:string,arg2:string,arg3:number):Promise<Array<json.RawMessage>>;

export function Send(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string):Promise<void>;
