// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Cancel():Promise<void>;

export function Compare(arg1:string,arg2:string):Promise<Array<services.AccessRow>>;

export function Copy(arg1:services.MirrorRequest):Promise<services.PlaybookResult>;
