// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['services']['MirrorService']['Cancel']();
}

export function Compare(arg1, arg2) {
  return window['go']['services']['MirrorService']['Compare'](arg1, arg2);
}

export function Copy(arg1) {
  return window['go']['services']['MirrorService']['Copy'](arg1);
}
