// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get() {
  return window['go']['services']['NotifyService']['Get']();
}

export function Set(arg1) {
  return window['go']['services']['NotifyService']['Set'](arg1);
}

export function Test() {
  return window['go']['services']['NotifyService']['Test']();
}
