// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Get():Promise<services.NotifyConfig>;

export function Set(arg1:services.NotifyConfig):Promise<void>;

export function Test():Promise<void>;
