// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['services']['OnPremService']['Connect'](arg1);
}

export function Connections() {
  return window['go']['services']['OnPremService']['Connections']();
}

export function DeleteConnection(arg1) {
  return window['go']['services']['OnPremService']['DeleteConnection'](arg1);
}

export function Disconnect() {
  return window['go']['services']['OnPremService']['Disconnect']();
}

export function PickCAFile() {
  return window['go']['services']['OnPremService']['PickCAFile']();
}

export function SaveConnection(arg1, arg2) {
  return window['go']['services']['OnPremService']['SaveConnection'](arg1, arg2);
}

export function Status() {
  return window['go']['services']['OnPremService']['Status']();
}
