// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {ldapx} from '../models';

export function Connect(arg1:string):Promise<services.OnPremStatus>;

export function Connections():Promise<Array<services.OnPremConnection>>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function PickCAFile():Promise<string>;

export function SaveConnection(arg1:ldapx.Config,arg2:string):Promise<services.OnPremConnection>;

export function Status():Promise<services.OnPremStatus>;
