// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function AddKey(arg1:string):Promise<Array<string>>;

export function Keys():Promise<Array<string>>;

export function List():Promise<Array<services.PackInfo>>;

export function OpenFolder():Promise<void>;

export function RemoveKey(arg1:string):Promise<Array<string>>;

export function Trust(arg1:string,arg2:string):Promise<Array<services.PackInfo>>;

export function Untrust(arg1:string):Promise<Array<services.PackInfo>>;
