// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function AddKey(arg1:string,arg2:string):Promise<Array<services.KeyInfo>>;

export function Disable(arg1:string):Promise<Array<services.PackInfo>>;

export function Enable(arg1:string):Promise<Array<services.PackInfo>>;

export function HubCatalog():Promise<services.HubView>;

export function HubInstall(arg1:string,arg2:string):Promise<Array<services.PackInfo>>;

export function Keys():Promise<Array<services.KeyInfo>>;

export function List():Promise<Array<services.PackInfo>>;

export function OpenFolder():Promise<void>;

export function RemoveKey(arg1:string):Promise<Array<services.KeyInfo>>;

export function SetHub(arg1:string):Promise<string>;

export function Trust(arg1:string,arg2:string):Promise<Array<services.PackInfo>>;

export function Untrust(arg1:string):Promise<Array<services.PackInfo>>;
