// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKey(arg1, arg2) {
  return window['go']['services']['PacksService']['AddKey'](arg1, arg2);
}

export function Disable(arg1) {
  return window['go']['services']['PacksService']['Disable'](arg1);
}

export function Enable(arg1) {
  return window['go']['services']['PacksService']['Enable'](arg1);
}

export function HubCatalog() {
  return window['go']['services']['PacksService']['HubCatalog']();
}

export function HubInstall(arg1, arg2) {
  return window['go']['services']['PacksService']['HubInstall'](arg1, arg2);
}

export function Keys() {
  return window['go']['services']['PacksService']['Keys']();
}

export function List() {
  return window['go']['services']['PacksService']['List']();
}

export function OpenFolder() {
  return window['go']['services']['PacksService']['OpenFolder']();
}

export function RemoveKey(arg1) {
  return window['go']['services']['PacksService']['RemoveKey'](arg1);
}

export function SetHub(arg1) {
  return window['go']['services']['PacksService']['SetHub'](arg1);
}

export function Trust(arg1, arg2) {
  return window['go']['services']['PacksService']['Trust'](arg1, arg2);
}

export function Untrust(arg1) {
  return window['go']['services']['PacksService']['Untrust'](arg1);
}
