// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Offboard(arg1) {
  return window['go']['services']['PlaybookService']['Offboard'](arg1);
}

export function Onboard(arg1) {
  return window['go']['services']['PlaybookService']['Onboard'](arg1);
}
