// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Cancel():Promise<void>;

export function Compromised(arg1:services.CompromisedRequest):Promise<services.CompromisedResult>;

export function Offboard(arg1:services.OffboardRequest):Promise<services.PlaybookResult>;

export function Onboard(arg1:services.OnboardRequest):Promise<services.PlaybookResult>;
