// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CSV(arg1, arg2) {
  return window['go']['services']['ReportsService']['CSV'](arg1, arg2);
}

export function Names() {
  return window['go']['services']['ReportsService']['Names']();
}
