// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMember(arg1, arg2) {
  return window['go']['services']['RolesService']['AddMember'](arg1, arg2);
}

export function List() {
  return window['go']['services']['RolesService']['List']();
}

export function Members(arg1) {
  return window['go']['services']['RolesService']['Members'](arg1);
}

export function RemoveMember(arg1, arg2, arg3) {
  return window['go']['services']['RolesService']['RemoveMember'](arg1, arg2, arg3);
}
