// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function AddMember(arg1:string,arg2:string):Promise<void>;

export function List():Promise<Array<json.RawMessage>>;

export function Members(arg1:string):Promise<Array<json.RawMessage>>;

export function RemoveMember(arg1:string,arg2:string,arg3:string):Promise<void>;
