// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function AppRoleAssignments(arg1:string):Promise<Array<json.RawMessage>>;

export function CAPolicies():Promise<Array<json.RawMessage>>;

export function OAuthGrants(arg1:string):Promise<Array<json.RawMessage>>;

export function ServicePrincipals(arg1:string,arg2:number):Promise<Array<json.RawMessage>>;
