// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppRoleAssignments(arg1) {
  return window['go']['services']['SecurityService']['AppRoleAssignments'](arg1);
}

export function CAPolicies() {
  return window['go']['services']['SecurityService']['CAPolicies']();
}

export function OAuthGrants(arg1) {
  return window['go']['services']['SecurityService']['OAuthGrants'](arg1);
}

export function ServicePrincipals(arg1, arg2) {
  return window['go']['services']['SecurityService']['ServicePrincipals'](arg1, arg2);
}
