// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Issues() {
  return window['go']['services']['ServiceHealthService']['Issues']();
}

export function Messages() {
  return window['go']['services']['ServiceHealthService']['Messages']();
}

export function Overview() {
  return window['go']['services']['ServiceHealthService']['Overview']();
}
