// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function Issues():Promise<Array<json.RawMessage>>;

export function Messages():Promise<Array<json.RawMessage>>;

export function Overview():Promise<Array<json.RawMessage>>;
