// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {json} from '../models';

export function Delete(arg1:string):Promise<void>;

export function Diff(arg1:string,arg2:string):Promise<services.SnapshotDiff>;

export function DiffLatest():Promise<services.SnapshotDiff>;

export function Get(arg1:string):Promise<json.RawMessage>;

export function List():Promise<Array<services.SnapshotMeta>>;

export function Take(arg1:string):Promise<services.SnapshotMeta>;
