// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['services']['SnapshotService']['Delete'](arg1);
}

export function Diff(arg1, arg2) {
  return window['go']['services']['SnapshotService']['Diff'](arg1, arg2);
}

export function DiffLatest() {
  return window['go']['services']['SnapshotService']['DiffLatest']();
}

export function Get(arg1) {
  return window['go']['services']['SnapshotService']['Get'](arg1);
}

export function List() {
  return window['go']['services']['SnapshotService']['List']();
}

export function Take(arg1) {
  return window['go']['services']['SnapshotService']['Take'](arg1);
}
