// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function AddChannelMember(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<json.RawMessage>;

export function AddTeamMember(arg1:string,arg2:string,arg3:boolean):Promise<json.RawMessage>;

export function ChannelMembers(arg1:string,arg2:string):Promise<Array<json.RawMessage>>;

export function Channels(arg1:string):Promise<Array<json.RawMessage>>;

export function CreateChannel(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<json.RawMessage>;

export function JoinedTeams(arg1:string):Promise<Array<json.RawMessage>>;

export function ListAllTeams(arg1:number):Promise<Array<json.RawMessage>>;

export function RemoveChannelMember(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveTeamMember(arg1:string,arg2:string):Promise<void>;

export function TeamMembers(arg1:string):Promise<Array<json.RawMessage>>;

export function Teamify(arg1:string):Promise<json.RawMessage>;
