// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChannelMember(arg1, arg2, arg3, arg4) {
  return window['go']['services']['TeamsService']['AddChannelMember'](arg1, arg2, arg3, arg4);
}

export function AddTeamMember(arg1, arg2, arg3) {
  return window['go']['services']['TeamsService']['AddTeamMember'](arg1, arg2, arg3);
}

export function ChannelMembers(arg1, arg2) {
  return window['go']['services']['TeamsService']['ChannelMembers'](arg1, arg2);
}

export function Channels(arg1) {
  return window['go']['services']['TeamsService']['Channels'](arg1);
}

export function CreateChannel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['TeamsService']['CreateChannel'](arg1, arg2, arg3, arg4, arg5);
}

export function JoinedTeams(arg1) {
  return window['go']['services']['TeamsService']['JoinedTeams'](arg1);
}

export function ListAllTeams(arg1) {
  return window['go']['services']['TeamsService']['ListAllTeams'](arg1);
}

export function RemoveChannelMember(arg1, arg2, arg3) {
  return window['go']['services']['TeamsService']['RemoveChannelMember'](arg1, arg2, arg3);
}

export function RemoveTeamMember(arg1, arg2) {
  return window['go']['services']['TeamsService']['RemoveTeamMember'](arg1, arg2);
}

export function TeamMembers(arg1) {
  return window['go']['services']['TeamsService']['TeamMembers'](arg1);
}

export function Teamify(arg1) {
  return window['go']['services']['TeamsService']['Teamify'](arg1);
}
