// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check() {
  return window['go']['services']['UpdateService']['Check']();
}

export function OpenReleasesPage(arg1) {
  return window['go']['services']['UpdateService']['OpenReleasesPage'](arg1);
}

export function SetAppContext(arg1) {
  return window['go']['services']['UpdateService']['SetAppContext'](arg1);
}
