// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function Block(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<json.RawMessage>;

export function LicenseDetails(arg1:string):Promise<Array<json.RawMessage>>;

export function List(arg1:string,arg2:number):Promise<Array<json.RawMessage>>;

export function MemberOf(arg1:string):Promise<Array<json.RawMessage>>;

export function ResetPassword(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<void>;

export function RevokeSessions(arg1:string,arg2:string):Promise<void>;

export function Snapshot(arg1:string):Promise<Record<string, any>>;

export function Unblock(arg1:string):Promise<void>;
