// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Check():Promise<services.WorkerInfo>;

export function ClientFingerprint():Promise<string>;

export function Pair(arg1:string,arg2:string):Promise<services.WorkerInfo>;

export function Status():Promise<services.WorkerInfo>;

export function Unpair():Promise<void>;
