// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check() {
  return window['go']['services']['WorkerService']['Check']();
}

export function ClientFingerprint() {
  return window['go']['services']['WorkerService']['ClientFingerprint']();
}

export function Pair(arg1, arg2) {
  return window['go']['services']['WorkerService']['Pair'](arg1, arg2);
}

export function Status() {
  return window['go']['services']['WorkerService']['Status']();
}

export function Unpair() {
  return window['go']['services']['WorkerService']['Unpair']();
}
