package services

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"time"

	wrt "github.com/wailsapp/wails/v2/pkg/runtime"

	"swissknife-app/internal/auth"
)

// CertInfo describes a certificate generated for a profile. Its PFX password
// stays in the backend: it is parked in the OS keychain and moves to the
// profile when the profile is saved (ADR-002).
type CertInfo struct {
	PfxPath    string    `json:"pfxPath"`
	CerPath    string    `json:"cerPath"`
	Thumbprint string    `json:"thumbprint"`
	NotAfter   time.Time `json:"notAfter"`
}

// GenerateCertificate creates a self-signed certificate for app-only sign-in
// (Exchange PowerShell accepts only certificates). The .pfx stays in the app
// data folder; the .cer next to it is what the operator uploads to the app
// registration under Certificates & secrets.
func (c *ConnectService) GenerateCertificate(name string) (*CertInfo, error) {
	safe := strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '-' || r == '_' {
			return r
		}
		return '-'
	}, strings.TrimSpace(name))
	if safe == "" {
		safe = "profile"
	}
	g, err := auth.GenerateCertificate("SwissKnifeGraph-" + safe)
	if err != nil {
		return nil, err
	}
	dir := filepath.Join(c.store.Dir(), "certs")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, err
	}
	base := filepath.Join(dir, safe+"-"+time.Now().Format("20060102-150405"))
	if err := os.WriteFile(base+".pfx", g.PFX, 0o600); err != nil {
		return nil, err
	}
	if err := os.WriteFile(base+".cer", g.CER, 0o644); err != nil {
		return nil, err
	}
	if err := c.store.SetPendingCertPassword(base+".pfx", g.Password); err != nil {
		_ = os.Remove(base + ".pfx")
		_ = os.Remove(base + ".cer")
		return nil, err
	}
	c.s.Record("connect.generateCertificate", g.Thumbprint, "expires="+g.NotAfter.Format("2006-01-02"), nil)
	return &CertInfo{PfxPath: base + ".pfx", CerPath: base + ".cer", Thumbprint: g.Thumbprint, NotAfter: g.NotAfter}, nil
}

// PickCertificate opens a file dialog for an existing PFX/PEM file.
func (c *ConnectService) PickCertificate() (string, error) {
	if c.s.Ctx().Value("events") == nil {
		return "", errors.New("file dialogs need the desktop app")
	}
	return wrt.OpenFileDialog(c.s.Ctx(), wrt.OpenDialogOptions{
		Title: "Certificate",
		Filters: []wrt.FileFilter{
			{DisplayName: "Certificate (*.pfx, *.p12, *.pem)", Pattern: "*.pfx;*.p12;*.pem"},
		},
	})
}

// RevealCertificate shows a generated certificate file in the system file
// manager (the .cer to upload). Only files in the app's certs folder qualify:
// the path comes from the webview and is handed to a shell command.
func (c *ConnectService) RevealCertificate(path string) error {
	dir := filepath.Join(c.store.Dir(), "certs")
	rel, err := filepath.Rel(dir, filepath.Clean(path))
	if err != nil || rel == "." || strings.HasPrefix(rel, "..") || filepath.IsAbs(rel) {
		return errors.New("not a certificate generated by this app")
	}
	if _, err := os.Stat(filepath.Join(dir, rel)); err != nil {
		return err
	}
	return revealInFolder(filepath.Join(dir, rel))
}
